[workspace]
members = [
    "corelib",
    "lmdb-sys",
    "blosc-sys",
    "sqlite-sys",
    "sandbox"
]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
panic = 'abort'